### PR TITLE
completion: Add zsh completion

### PR DESCRIPTION
**Pull request by zchee**
Add zsh completion.

If you do not like this directory structure (`contrib/completion/{zsh|bash}`), will fix.
Thanks.

### CODE REVIEW

**Comment by zchee** [comment]
ah failed CI :(
Why...?

**Comment by mattn** [comment]
This is not your's problem. It's mine.

**Comment by mattn** [comment]
Thank you

**Comment by zchee** [comment]
@mattn Thanks!
If any command is added, I will follow-up as much as possible.

**Comment by mattn** [comment]
BTW, do you know below?

```
$ goravis --completion-script-zsh
```

**Comment by zchee** [comment]
ah, yes.

but `eval $(goravis --completion-script-zsh)` is simple bash-completion wrapper. does not displaying command description.(I tested, but I might be wrong)
So, I made a pure zsh completion.

**Comment by mattn** [comment]
Ah, make sense.

**Pull request merged**
